import type { Metadata } from "next";
import { Geist, Geist_Mono, Sora, Nunito, Inter, DM_Sans } from "next/font/google";
import "./globals.css";

const dmsans = DM_Sans({
  variable: "--dm-sans"
})

const inter = Inter ({
  variable :'--font-inter'
})

const nunito = Nunito({
  variable :'--font-nunito'
})

const sora = Sora({
  variable : "--font-sora",

})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sora.variable} ${nunito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
