import type { Metadata } from "next";
import { Sora, Nunito, Inter, DM_Sans } from "next/font/google";
import "./globals.css";

const dmsans = DM_Sans({
  variable: "--dm-sans",
  display: 'swap',
})

const inter = Inter ({
  variable :'--font-inter',
  display: 'swap',
})

const nunito = Nunito({
  variable :'--font-nunito',
  display: 'swap',
})

const sora = Sora({
  variable : "--font-sora",
  display: 'swap',
})

// Temporarily commented out Geist fonts due to Turbopack compatibility issues
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
//   display: 'swap',
//   fallback: ['system-ui', 'arial'],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
//   display: 'swap',
//   fallback: ['ui-monospace', 'monospace'],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} ${nunito.variable} ${inter.variable} ${dmsans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
